import { useState } from "react";
import { useAnalysisStore } from "@/store/useAnalysisStore";
import { Copy, Download, Check, ChevronDown, ChevronUp } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { ValiSearchAnalysis, StackBlock } from "@/types/analysis";

/* ─── Helpers ─────────────────────────────────────────────── */
function stackToList(s: StackBlock): string[] {
  return [s.frontend, s.backend, s.database, s.apis].filter(Boolean);
}

/* ─── File generators ─────────────────────────────────────── */

function genCursorRules(a: ValiSearchAnalysis): string {
  const techs = [...stackToList(a.tech_stack.mvp).slice(0, 4), ...stackToList(a.tech_stack.scalable).slice(0, 3)].join(", ");
  const features = a.product_strategy.mvp_features.map((f) => `  - ${f}`).join("\n");
  const buildSteps = a.build_mode.modules.slice(0, 6).map((s, i) => `  ${i + 1}. ${s}`).join("\n");

  return `# .cursorrules — ${a.branding.name_suggestions[0]}
# Generated by ValiSearch AI Startup Intelligence Platform

## Project Overview
${a.idea_analysis.summary}

## One-Liner
${a.idea_analysis.one_liner}

## Tech Stack
${techs}

## MVP Features (implement in order)
${features}

## Build Steps
${buildSteps}

## Code Style
- Prefer TypeScript strict mode
- Use functional components with hooks
- Colocate tests with source files
- No class components
- Prefer composition over inheritance
- Extract reusable logic into custom hooks
- Use named exports for components

## Architecture Rules
- Keep components under 200 lines — extract if larger
- Use ${a.tech_stack.mvp.backend} for backend API
- Validate all inputs with Zod schemas
- No hardcoded secrets — use environment variables only

## Naming Conventions
- Components: PascalCase
- Hooks: camelCase prefixed with "use"
- Files: kebab-case
- DB tables: snake_case

## AI Coding Instructions
When I ask you to build a feature:
1. Write the type definitions first
2. Implement the core logic
3. Write the UI component
4. Add error handling
5. Handle loading states

## Market
${a.validation.market_demand}

## Key Differentiators
${a.competitor_analysis.differentiation_strategy}
`;
}

function genVSCodeTasks(a: ValiSearchAnalysis): string {
  const tasks = a.kanban.backlog.slice(0, 6).map((task, i) => ({
    label: `${i + 1}. ${task.title}`,
    type: "shell",
    command: `echo "Starting: ${task.title.replace(/"/g, "'")} (${task.estimated_effort})"`,
    group: { kind: "build", isDefault: i === 0 },
    problemMatcher: [],
    detail: task.description,
  }));

  return JSON.stringify({ version: "2.0.0", tasks }, null, 2);
}

function genProjectMd(a: ValiSearchAnalysis): string {
  const mvpStack = stackToList(a.tech_stack.mvp).join(", ");
  const features = a.product_strategy.mvp_features.map((f) => `- ${f}`).join("\n");
  const competitors = a.competitor_analysis.competitors.map((c) => `- **${c.name}**: ${c.weaknesses[0]}`).join("\n");
  const allTasks = [...a.kanban.backlog, ...a.kanban.in_progress, ...a.kanban.completed]
    .slice(0, 10)
    .map((t) => `| ${t.title} | ${t.priority} | ${t.estimated_effort} |`)
    .join("\n");

  return `# ${a.branding.name_suggestions[0]} — Project Spec
> ${a.idea_analysis.summary}

## One-Liner
${a.idea_analysis.one_liner}

## Market Opportunity
${a.validation.market_demand}

## Solution
${a.competitor_analysis.differentiation_strategy}

## Tech Stack (MVP)
${mvpStack}

## MVP Features
${features}

## Sprint Plan
| Task | Priority | Effort |
|------|----------|--------|
${allTasks}

## Market
- TAM: ${a.market_research.tam_sam_som.tam}
- SAM: ${a.market_research.tam_sam_som.sam}
- SOM: ${a.market_research.tam_sam_som.som}

## Revenue
- Model: ${a.monetization.pricing_model}
- Streams: ${a.monetization.revenue_streams.join(", ")}

## Competitors
${competitors}

## Risks
${a.validation.risks.map((r) => `- ${r}`).join("\n")}

---
*Generated by ValiSearch — AI Startup Intelligence Platform*
`;
}

function genLovablePrompt(a: ValiSearchAnalysis): string {
  const stack = stackToList(a.tech_stack.mvp).join(", ");
  const features = a.product_strategy.mvp_features.join(", ");
  return `Build a SaaS web app called "${a.branding.name_suggestions[0]}".

CONCEPT: ${a.idea_analysis.summary}

TAGLINE: ${a.branding.taglines[0]}

TECH STACK: ${stack}

PAGES TO BUILD:
${a.user_flow.journey_steps.map((s, i) => `${i + 1}. ${s}`).join("\n")}

CORE FEATURES:
${a.product_strategy.mvp_features.map((f) => `- ${f}`).join("\n")}

KEY FEATURES: ${features}

DESIGN:
- Dark premium UI (background #0A0A0A, white text)
- Clean sans-serif typography
- Subtle borders at 8% opacity
- Minimal indigo/violet accent color
- Dashboard layout with sidebar navigation

PRICING:
${a.monetization.pricing_tiers.map((t) => `- ${t.name}: ${t.price_hint}`).join("\n")}

Make it look like a professional SaaS tool similar to Linear or Vercel.
`;
}

function genBoltPrompt(a: ValiSearchAnalysis): string {
  const stack = stackToList(a.tech_stack.mvp).join(", ");
  return `Create a full-stack web application: "${a.branding.name_suggestions[0]}"

Description: ${a.idea_analysis.summary}

Stack: ${stack}

Features to implement:
${a.product_strategy.mvp_features.map((f, i) => `${i + 1}. ${f}`).join("\n")}

User flow:
${a.user_flow.journey_steps.join(" → ")}

Design system:
- Dark theme with #0A0A0A background
- White text with opacity variants
- Indigo accent (#6366f1)
- Rounded corners (12px), subtle borders
- Inter font family

Include: Auth, Dashboard layout, ${a.product_strategy.mvp_features[0]}, Settings page
`;
}

function genVSCodeSettings(a: ValiSearchAnalysis): string {
  return JSON.stringify({
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "typescript.preferences.importModuleSpecifier": "relative",
    "editor.codeActionsOnSave": { "source.fixAll.eslint": "explicit" },
    "files.exclude": { "**/node_modules": true, "**/.git": true, "**/dist": true },
    "search.exclude": { "**/node_modules": true, "**/dist": true },
    "editor.rulers": [100],
    "editor.tabSize": 2,
    "editor.detectIndentation": false,
    "[typescript]": { "editor.defaultFormatter": "esbenp.prettier-vscode" },
    "[typescriptreact]": { "editor.defaultFormatter": "esbenp.prettier-vscode" },
    "github.copilot.chat.codeGeneration.instructions": [
      { "text": `Project: ${a.branding.name_suggestions[0]} — ${a.idea_analysis.one_liner}` },
      { "text": `Tech stack: ${stackToList(a.tech_stack.mvp).join(", ")}` },
      { "text": "Use TypeScript strict mode, functional components, and Zod validation." },
    ],
  }, null, 2);
}

/* ─── Types ──────────────────────────────────────────────── */
type FileSpec = {
  key: string;
  label: string;
  filename: string;
  description: string;
  generate: (a: ValiSearchAnalysis) => string;
  category: "cursor" | "vscode" | "nocode";
};

const FILES: FileSpec[] = [
  {
    key: "cursorrules",
    label: ".cursorrules",
    filename: ".cursorrules",
    description: "AI context file for Cursor IDE — tells the AI about your stack, rules, and project",
    generate: genCursorRules,
    category: "cursor",
  },
  {
    key: "project",
    label: "PROJECT.md",
    filename: "PROJECT.md",
    description: "Complete project specification — share with team or paste into Claude/ChatGPT",
    generate: genProjectMd,
    category: "cursor",
  },
  {
    key: "tasks",
    label: "tasks.json",
    filename: "tasks.json",
    description: "VS Code task runner — run sprint tasks directly from the command palette",
    generate: genVSCodeTasks,
    category: "vscode",
  },
  {
    key: "settings",
    label: "settings.json",
    filename: "settings.json",
    description: "VS Code workspace settings — formatters, linting, Copilot instructions",
    generate: genVSCodeSettings,
    category: "vscode",
  },
  {
    key: "lovable",
    label: "Lovable Prompt",
    filename: "lovable-prompt.txt",
    description: "Ready-to-paste prompt for Lovable.dev — generates your full-stack app",
    generate: genLovablePrompt,
    category: "nocode",
  },
  {
    key: "bolt",
    label: "Bolt.new Prompt",
    filename: "bolt-prompt.txt",
    description: "Ready-to-paste prompt for Bolt.new — generates your full-stack app instantly",
    generate: genBoltPrompt,
    category: "nocode",
  },
];

/* ─── File card ──────────────────────────────────────────── */
function FileCard({ spec, analysis }: { spec: FileSpec; analysis: ValiSearchAnalysis }) {
  const [copied, setCopied] = useState(false);
  const [expanded, setExpanded] = useState(false);
  const content = spec.generate(analysis);

  const copy = () => {
    navigator.clipboard.writeText(content).catch(() => {});
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const download = () => {
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = spec.filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const BADGE_STYLE: Record<string, string> = {
    cursor: "text-violet-400 bg-violet-500/10 border-violet-500/20",
    vscode: "text-blue-400 bg-blue-500/10 border-blue-500/20",
    nocode: "text-green-400 bg-green-500/10 border-green-500/20",
  };

  const BADGE_LABEL: Record<string, string> = {
    cursor: "Cursor AI",
    vscode: "VS Code",
    nocode: "No-Code",
  };

  return (
    <div className="rounded-xl border border-white/[0.07] bg-white/[0.02] overflow-hidden">
      <div className="flex items-start gap-3 p-4">
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-1">
            <code className="text-[13px] font-bold text-white/80 font-mono">{spec.label}</code>
            <span className={`text-[9px] font-semibold uppercase tracking-wider px-1.5 py-0.5 rounded-full border ${BADGE_STYLE[spec.category]}`}>
              {BADGE_LABEL[spec.category]}
            </span>
          </div>
          <p className="text-[12px] text-muted-foreground leading-snug">{spec.description}</p>
          <div className="text-[10.5px] text-white/20 font-mono mt-1">{spec.filename}</div>
        </div>
        <div className="flex items-center gap-1.5 shrink-0">
          <button
            onClick={() => setExpanded((x) => !x)}
            className="p-1.5 rounded-lg text-white/30 hover:text-white/70 hover:bg-white/[0.06] transition-colors"
            title="Preview"
          >
            {expanded ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
          </button>
          <button
            onClick={copy}
            className="p-1.5 rounded-lg text-white/30 hover:text-white/70 hover:bg-white/[0.06] transition-colors"
            title="Copy"
          >
            {copied ? <Check className="h-4 w-4 text-green-400" /> : <Copy className="h-4 w-4" />}
          </button>
          <button
            onClick={download}
            className="p-1.5 rounded-lg text-white/30 hover:text-white/70 hover:bg-white/[0.06] transition-colors"
            title="Download"
          >
            <Download className="h-4 w-4" />
          </button>
        </div>
      </div>

      {expanded && (
        <div className="border-t border-white/[0.06] max-h-72 overflow-y-auto">
          <pre className="p-4 text-[11px] text-white/50 font-mono leading-relaxed whitespace-pre-wrap break-words">
            {content}
          </pre>
        </div>
      )}
    </div>
  );
}

/* ─── Main ───────────────────────────────────────────────── */
export function IdeBridgeSection() {
  const analysis = useAnalysisStore((s) => s.analysis);
  if (!analysis) return null;

  const downloadAll = () => {
    FILES.forEach((spec, i) => {
      setTimeout(() => {
        const content = spec.generate(analysis);
        const blob = new Blob([content], { type: "text/plain" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = spec.filename;
        a.click();
        URL.revokeObjectURL(url);
      }, i * 350);
    });
  };

  const categories = [
    { key: "cursor", label: "Cursor AI", subtitle: "AI-native IDE with codebase understanding" },
    { key: "vscode", label: "VS Code", subtitle: "Workspace settings and task runner config" },
    { key: "nocode", label: "No-Code Builders", subtitle: "Ready-to-paste prompts for Lovable & Bolt" },
  ] as const;

  return (
    <div className="space-y-6 max-w-4xl">
      <div className="flex items-start justify-between flex-wrap gap-3">
        <div>
          <h2 className="text-xl font-bold tracking-tight">IDE Bridge</h2>
          <p className="text-[13px] text-muted-foreground mt-1">
            Export your project spec to Cursor, VS Code, Lovable, or Bolt.new — ready to paste and build
          </p>
        </div>
        <Button
          size="sm"
          variant="outline"
          className="gap-2 h-8 text-[12px]"
          onClick={downloadAll}
        >
          <Download className="h-3.5 w-3.5" /> Download All ({FILES.length} files)
        </Button>
      </div>

      {categories.map(({ key, label, subtitle }) => (
        <div key={key} className="space-y-3">
          <div>
            <div className="text-[13px] font-semibold text-white/70">{label}</div>
            <div className="text-[11px] text-muted-foreground/50 mt-0.5">{subtitle}</div>
          </div>
          <div className="space-y-2">
            {FILES.filter((f) => f.category === key).map((spec) => (
              <FileCard key={spec.key} spec={spec} analysis={analysis} />
            ))}
          </div>
        </div>
      ))}
    </div>
  );
}
